<a href="https://colab.research.google.com/github/RodriCalle/ComplejidadAlgoritmica/blob/main/6_Divide_y_Venceras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Master Theorem

$$ T(n) = aT(\frac{n}{b}) + O(n^k) $$

So...

$$
T(n) = \begin{equation}
\left\{ 
  \begin{aligned}
    O(n^k)           && a < b^k\\
    O(n^k\,log\,n)   && a = b^k\\
    O(n^{log_b\,a})  && a > b^k
  \end{aligned}
  \right.
\end{equation}
$$

In [48]:
import random

lst = list(range(10))
random.shuffle(lst)
print(lst)

[9, 3, 8, 1, 4, 7, 2, 5, 0, 6]


##Multiplicacion de dos numeros

In [49]:
def mult(a, b, n):
  if n == 1:
    return a * b

  ai = a // 10**(n//2)
  ad = a % 10**(n//2)
  bi = b // 10**(n//2)
  bd = b % 10**(n//2)
  z1 = mult(ai, bi, n//2) * 10**n
  z2 = (mult(ai, bd, n//2) + mult(ad, bi, n//2)) * 10**(n//2)
  z3 = mult(ad, bd, n//2)
  
  return z1 + z2 + z3

a = 548929495
b = 102043934
n = 16
res = mult(a, b, n)
print(res)

56014925158433330


##El mayor de un arreglo

###Fuerza Bruta

In [50]:
def bfmax(a):
  m = a[0]
  for i in range(1, len(a)):
    if a[i] > m:
      m = a[i]
  return m

In [51]:
bfmax(lst)

9

### Divide y venceras

In [52]:
def dcmax(a, i, f):
  if i == f:
    return a[i]
  
  mid = (i + f) // 2
  maxleft = dcmax(a, i, mid)
  maxright = dcmax(a, mid + 1, f)
  
  return maxleft if maxleft > maxright else maxright

dcmax(lst, 0, len(lst)-1)

9

$$ T(n) = 2T(\frac{n}{2}) + O(1) $$


$$
a = 2\\
b = 2\\
k = 0
$$

$$
T(n) = n^{\log_2{2}}\\
T(n) = n\\
T(n) \implies O(n)
$$

##Sumatoria de un arreglo

In [53]:
def suma(ini, fin, arr):
  if (ini == fin):
    return arr[ini]
  else:
    mitad = (ini+fin)//2
    x = suma(ini, mitad, arr)
    y = suma(mitad+1, fin,arr)
    return x+y
  
suma(0,len(lst)-1, lst)

45

##Multiplicacion de matrices

para matrices donde $n = 2^k \,,\, k \in N$

### Classic way

In [54]:
def matmul(a, b):
  n = len(a)
  c = [[0]*n for _ in range(n)]
  for i in range(n):
    for j in range(n):
      accum = 0
      for k in range(n):
        accum += a[i][k] * b[k][j]
      c[i][j] = accum
  return c

In [55]:
import numpy as np

In [56]:
n = 8
a = np.array(list(range(n*n))).reshape((n, n))
b = np.array(list(range(n*n))).reshape((n, n))
print(a)
print(b)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]


In [57]:
c = matmul(a, b)
np.array(c)

array([[ 1120,  1148,  1176,  1204,  1232,  1260,  1288,  1316],
       [ 2912,  3004,  3096,  3188,  3280,  3372,  3464,  3556],
       [ 4704,  4860,  5016,  5172,  5328,  5484,  5640,  5796],
       [ 6496,  6716,  6936,  7156,  7376,  7596,  7816,  8036],
       [ 8288,  8572,  8856,  9140,  9424,  9708,  9992, 10276],
       [10080, 10428, 10776, 11124, 11472, 11820, 12168, 12516],
       [11872, 12284, 12696, 13108, 13520, 13932, 14344, 14756],
       [13664, 14140, 14616, 15092, 15568, 16044, 16520, 16996]])

### Divide and conquer way

In [58]:
def dcmatmul(a, b, c, ri, rf, ci, cf):
  n = len(a)
  if ri == rf:
    accum = 0
    for k in range(n):
      accum += a[ri][k] * b[k][cf]

    c[ri][cf] = accum
  else:
    rmid = (ri + rf) // 2
    cmid = (ci + cf) // 2
    dcmatmul(a, b, c, ri, rmid, ci, cmid)
    dcmatmul(a, b, c, rmid+1, rf, ci, cmid)
    dcmatmul(a, b, c, ri, rmid, cmid +1, cf)
    dcmatmul(a, b, c, rmid+1, rf, cmid + 1, cf)

In [59]:
n = 8
a = np.array(list(range(n*n))).reshape((n, n))
b = np.array(list(range(n*n))).reshape((n, n))
c = np.zeros((n, n))
dcmatmul(a, b, c, 0, n-1, 0, n-1)
print(c)

[[ 1120.  1148.  1176.  1204.  1232.  1260.  1288.  1316.]
 [ 2912.  3004.  3096.  3188.  3280.  3372.  3464.  3556.]
 [ 4704.  4860.  5016.  5172.  5328.  5484.  5640.  5796.]
 [ 6496.  6716.  6936.  7156.  7376.  7596.  7816.  8036.]
 [ 8288.  8572.  8856.  9140.  9424.  9708.  9992. 10276.]
 [10080. 10428. 10776. 11124. 11472. 11820. 12168. 12516.]
 [11872. 12284. 12696. 13108. 13520. 13932. 14344. 14756.]
 [13664. 14140. 14616. 15092. 15568. 16044. 16520. 16996.]]
